make nitpicks
redhat-cop/vault-config-operator pull request #46
Opened 2022-04-10 22:18 UTC by raffaelespazzoli

tested OLM deployment

Signed-off-by: raffaelespazzoli <raffaele.spazzoli@gmail.com>

2022-04-11 19:37 UTC, trevorbox approved these changes
LGTM

2022-04-11 21:28 UTC, sabre1041 requested changes

2022-04-11 21:28 UTC, sabre1041 commented on Makefile
> +	$(KIND) create cluster --image docker.io/kindest/node:$(KUBECTL_VERSION) --config=./integration/cluster-kind.yaml
Lets allow `docker.io` to be overridden via a variable

2022-04-12 02:58 UTC, sabre1041 approved these changes
Approving for now

2022-04-12 02:58 UTC, merged